version: '3.8'

services:
  spa:
    container_name: ${FRONTEND_CONTAINER_NAME}
    image: matheusb432/tma-spa
    env_file:
      - .env
    ports:
      - '${SPA_PORT}:81'

  api:
    container_name: ${BACKEND_CONTAINER_NAME}
    image: matheusb432/tma-api
    env_file:
      - .env
    ports:
      - '${API_PORT}:80'

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: 'mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04'
    env_file:
      - .env
    environment:
      SA_PASSWORD: '${DB_PASSWORD}'
      ACCEPT_EULA: 'Y'
    ports:
      - '${DB_PORT}:1433'
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata:
